spring:
  application:
    name: lefriend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${lefriend.mysql.host:localhost}:3306/${lefriend.mysql.database:lefriend}
    username: root
    password: ${lefriend.mysql.password:123456}
  session:
    timeout: 86400 # 一天时间
    # 默认redis。。。，如果引入了spring session data redis
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: ${lefriend.redis.host:localhost}
    database: 1

server:
  port: 8080
  servlet:
    context-path: /api
  reactive:
    session:
      cookie:
        domain: localhost
  tomcat:
    threads:
      max: 400

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
